#!/bin/bash -e



if dpkg-maintscript-helper supports rm_conffile 2>/dev/null; then
  dpkg-maintscript-helper rm_conffile /etc/kde3/kdeglobals 6.0.1 -- "$@"
fi

if [ "${1}" = "configure" ] && [ "$2" != "" ] ; then

    if dpkg --compare-versions ${2} lt 0.3.11 && dpkg --compare-versions ${2} gt 0.3.5; then
        if test -x /var/lib/dpkg/info/libgnome2-common.postinst; then
            /var/lib/dpkg/info/libgnome2-common.postinst configure
        fi
    fi
fi

if [ "$1" = "configure" -o "$1" = "abort-upgrade" ]; then
    # Alternatives for the background
    update-alternatives --install \
        /usr/share/images/neptune-base/desktop-background \
        desktop-background \
        /usr/share/images/neptune-base/neptune-wp.png 60

    # Alternatives for the splash
    update-alternatives --install \
        /usr/share/images/neptune-base/desktop-splash \
        desktop-splash \
        /usr/share/images/neptune-base/neptune-splash.png 50

    # Alternatives for grub
    update-alternatives --install \
        /usr/share/images/neptune-base/desktop-grub.png \
        desktop-grub \
        /usr/share/images/neptune-base/neptune-grub.png 15

    update-alternatives --install \
        /usr/share/images/neptune-base/desktop-grub.png \
        desktop-grub \
        /usr/share/images/neptune-base/neptune-grub-widescreen.png 14

    update-alternatives --install \
        /usr/share/images/neptune-base/desktop-grub.png \
        desktop-grub \
        /usr/share/images/neptune-base/moreblue-orbit-grub.png 10

    # GRUB background
    if which update-grub2 > /dev/null ; then
        sync
        update-grub2 || true
    fi

    # Splashy
    #if [ -x /sbin/splashy_config ] && [ -w /etc/splashy/config.xml ]; then
    #    splashy_config --set-theme spacefun
    #fi

    # Plymouth
    if [ -x /usr/sbin/plymouth-set-default-theme ];
    then
      plymouth-set-default-theme caledonia-neptune ||true
    fi

    if [ -x /usr/sbin/update-initramfs ]; then
        update-initramfs -u
    fi
    
    # Cursor theme
    update-alternatives --install \
	/usr/share/icons/default/index.theme \
	x-cursor-theme \
	/etc/X11/cursors/bridge.theme 50
fi
