#!/bin/sh -e

#DEBHELPER#

if dpkg-maintscript-helper supports rm_conffile 2>/dev/null; then
  dpkg-maintscript-helper rm_conffile /etc/kde3/kdeglobals 6.0.1 -- "$@"
fi

unhide() {

   if [ -e /usr/share/applications/gnome-mplayer.desktop ]; then
      dpkg-divert --package neptune-base --remove --rename --divert /usr/share/neptune-base/hidden/gnome-mplayer.desktop /usr/share/applications/gnome-mplayer.desktop
    fi
}

basefiles() {

    if [ -e /etc/os-release ]; then
      dpkg-divert --package neptune-base --remove --rename --divert /etc/os-release.orig /etc/os-release
      dpkg-divert --package neptune-base --remove --rename --divert /usr/lib/os-release.orig /usr/lib/os-release
    fi
    if [ -e /etc/issue ]; then
      dpkg-divert --package neptune-base --remove --rename --divert /etc/issue.orig /etc/issue
    fi
    if [ -e /etc/issue.net ]; then
      dpkg-divert --package neptune-base --remove --rename --divert /etc/issue.net.orig /etc/issue.net
    fi
}

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    if which update-grub2 > /dev/null ; then
        update-grub2 || true
    fi
    dpkg-divert --package neptune-base --remove --rename --divert /usr/share/kde4/apps/plasma-desktop/init/00-defaultLayout.js.orig /usr/share/kde4/apps/plasma-desktop/init/00-defaultLayout.js
    dpkg-divert --package neptune-base --remove --rename --divert /usr/share/kde4/apps/plasma-desktop/updates/addShowActivitiesManagerPlasmoid.js.orig /usr/share/kde4/apps/plasma-desktop/updates/addShowActivitiesManagerPlasmoid.js
    unhide
    basefiles
fi

#if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
#    if [ -x /usr/sbin/plymouth-set-default-theme ];
#    then
#      plymouth-set-default-theme -r -R ||true
#    fi
#fi


